language: go
go:
- '1.11'
deploy:
  provider: releases
  api_key:
    secure: cQb9w1glHiG6zKmOXJSBZZg+3JxDjYnR1q8WhuvFc6DTpaYVYmbkN2Bx3HVZeotBeIMGZf45C54339dArlIzm0Q4+dYewWemz5W2l14wEkjiE9IPdpgowCzj4hINq2SU+mBq0jI3AvYpFWL692hLW3Ty6hhn78KVl4LYJEtA136lk/9RT/pLF0uBuyE4HXgqG83v70/KW4bz5MaQYQpd/mWjybYEsecG+TF5pm/VHogxzg14KjyfKwkvVZTVBPj5LwRxbU3fnsOAv32OaQ6y7m0L9Vp1bJdtqJcvE2IejpLQZB0wDrO0Y5+vMt3bT2GSZON2qbIz4PazyQW8SchvkaImnsykZCQHI+kTjD6z0r34wpr9xr7vw9pcawNaYbM90O99ep7W6veOqOUkTGif0n5pV4huxJSDrUAma8APmk/CMnWFOZrD9GRF0fAWdK1skEMMVAKdhe1elAsYEgjRSLrykSxlp7VgN/Ueyx8ZQ0hvVNT71S6AwF0B/oWuIVnVKCTjwgq2ufdBxrkcfL/iGOvNQeGRWy0YfNcepBhF6GM7mKtVxPq3HUwWFqLpbgSla6Zw5nCiszekE1DkBgjAtt3406EfH6BkqVeIGv9+K5A14RNzLf2+g6ItYVhx3J1+g7ycx+1csbpK5BSWcVzJm5QNsHykaeFvaaEhF5HQu4Y=
  file_glob: true
  file: build/kpatch-*
  skip_cleanup: true
  on:
    tags: true
    repo: mikesimons/kpatch
install:
- make dev-deps
script:
- make all
env:
  global:
  - CGO_ENABLED=0